### PR TITLE
Improve `Destination.sdkPlatformFrameworkPaths()`

### PR DESCRIPTION
**Pull request by neonichu**
We should not ignore errors or an empty SDK platform path since that means XCTest imports and test execution might silently fail on macOS with no indication to what the problem is.

### CODE REVIEW

**Review by tomerd — APPROVED** [review]

**Comment by neonichu** [comment]
Linux self-hosted is failing with 

```
<EXPR>:0: error: TestDiscoveryTests.testSubclassedTestClassTests : threw error "terminated(1): /home/build-user/swiftpm/.build/x86_64-unknown-linux-gnu/debug/swift-test --package-path /tmp/Miscellaneous_TestDiscovery_Subclass.1HY8Nx/Miscellaneous_TestDiscovery_Subclass --configuration debug output:
    /tmp/Miscellaneous_TestDiscovery_Subclass.1HY8Nx/Miscellaneous_TestDiscovery_Subclass/.build/x86_64-unknown-linux-gnu/debug/SubclassPackageTests.xctest: error while loading shared libraries: libswift_RegexParser.so: cannot open shared object file: No such file or directory
```

which seems like a broken toolchain potentially?

Windows is failing somewhere early in the process as well.

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by MaxDesiatov** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
Of course things are passing after adding extra logging 🥲

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
```
[error]: Invalid manifest
/var/folders/pf/p5g2vb2j0yx1x6vlmxdppc700000gn/T/spm-tests-testSimpleAPI.qYJkUF/MyPkg/Package.swift:4:8: error: no such module 'PackageDescription'
import PackageDescription
       ^
```

Hm, not sure why we aren't seeing the new `compilerCommandLine` stuff I added.

**Comment by neonichu** [comment]
> Hm, not sure why we aren't seeing the new compilerCommandLine stuff I added.

Ah, it is being set in the wrong place.

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
Seems reasonable that this fails? We're looking for the PD libs in the installation directory before installing.

```
[error]: Invalid manifest (compiled with: ["/Users/ec2-user/jenkins/workspace/swift-package-manager-PR-macos-smoke-test/branch-main/build/buildbot_incremental/toolchain-macosx-x86_64/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc", "-vfsoverlay", "/var/folders/pf/p5g2vb2j0yx1x6vlmxdppc700000gn/T/TemporaryDirectory.dHFMod/vfs.yaml", "-L", "/Users/ec2-user/jenkins/workspace/swift-package-manager-PR-macos-smoke-test/branch-main/build/buildbot_incremental/toolchain-macosx-x86_64/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/pm/ManifestAPI", "-lPackageDescription", "-Xlinker", "-rpath", "-Xlinker", "/Users/ec2-user/jenkins/workspace/swift-package-manager-PR-macos-smoke-test/branch-main/build/buildbot_incremental/toolchain-macosx-x86_64/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/pm/ManifestAPI", "-target", "x86_64-apple-macosx10.15", "-sdk", "/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk", "-F", "/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks", "-I", "/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib", "-L", "/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib", "-swift-version", "5", "-I", "/Users/ec2-user/jenkins/workspace/swift-package-manager-PR-macos-smoke-test/branch-main/build/buildbot_incremental/toolchain-macosx-x86_64/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/pm/ManifestAPI", "-sdk", "/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk", "-package-description-version", "5.7.0", "/var/folders/pf/p5g2vb2j0yx1x6vlmxdppc700000gn/T/spm-tests-testSimpleAPI.MrySgk/MyPkg/Package.swift", "-o", "/var/folders/pf/p5g2vb2j0yx1x6vlmxdppc700000gn/T/TemporaryDirectory.tJZRZ9/mypkg-manifest"])
/var/folders/pf/p5g2vb2j0yx1x6vlmxdppc700000gn/T/spm-tests-testSimpleAPI.MrySgk/MyPkg/Package.swift:4:8: error: no such module 'PackageDescription'
import PackageDescription
       ^
```

Not sure what changed to make us to do that.

**Comment by neonichu** [comment]
Probably we're ending up in the fallback case, instead of the testing case here:

```
// this tests if we are debugging / testing SwiftPM with SwiftPM
        if localFileSystem.exists(applicationPath.appending(component: "swift-package")) {
            return .init(
                manifestLibraryPath: applicationPath,
                pluginLibraryPath: applicationPath
            )
        }

        // we are using a SwiftPM outside a toolchain, use the compiler path to compute the location
        return .init(swiftCompilerPath: swiftCompilerPath)
```

**Comment by neonichu** [comment]
Not sure I understand how this ever works? `applicationPath` will be `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Xcode/Agents/xctest` so we'll always use search paths relative to `swiftCompilerPath` when running a test that doesn't shell out.

**Comment by neonichu** [comment]
Oh I see, this is why we're setting up a bit of a fake toolchain as part of bootstrap, so I think the issue is that we're directly pointing to the installed `swiftc` rather than to the symlink in the fake toolchain. I think what broke things is #4213, because with that we're using the installed `swiftc` directly.

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
OK, I think the failure in `testSimpleAPI` is understood now, but that still leaves `testBuildCompleteMessage` and `testNonC99NameExecutablePackage` which aren't clear to me, yet.

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
Got the `error: cannot find 'XCTAssertEqual' in scope` once, so the issue is definitely still present. Unfortunately, it only happens 10-20% of the time.

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Review by tomerd — APPROVED** [review]

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
```
Test Case '-[CommandsTests.BuildToolTests testBuildCompleteMessage]' started./Users/ec2-user/jenkins/workspace/swift-package-manager-PR-macos-smoke-test/branch-main/swiftpm/Tests/CommandsTests/BuildToolTests.swift:299: error: -[CommandsTests.BuildToolTests testBuildCompleteMessage] : XCTAssertTrue failed - unexpected failure matching 'Building for debugging...
[1/3] Compiling Foo Foo.swift
[2/3] Compiling Foo main.swift
[3/4] Merging module Foo
[3/4] Linking Foo
Build complete! (2.90s)
' against pattern regex("\\[[1-9][0-9]*\\/[1-9][0-9]*\\] Compiling")Test Case '-[CommandsTests.BuildToolTests testBuildCompleteMessage]' failed (35.475 seconds).Test Suite 'BuildToolTests' failed at 2022-11-08 05:16:45.215.
	 Executed 1 test, with 1 failure (0 unexpected) in 35.475 (35.475) secondsTest Suite 'SwiftPMPackageTests.xctest' failed at 2022-11-08 05:16:45.215.
```

**Comment by neonichu** [comment]
Ah interesting, I think I understand the failure now. There's no different failure message for matching vs. *not* matching, so this is probably from the second half of the test where it wants to assert that we are *not* compiling anything.

**Comment by neonichu** [comment]
Fix for the failure message: https://github.com/apple/swift-tools-support-core/pull/366

**Comment by neonichu** [comment]
Now the question remains what's causing the failure, can't repro it locally after ~700 iterations of the test. It does seem most likely that a regression in incremental builds would have been caused by https://github.com/apple/swift-package-manager/pull/5846 though.

**Comment by neonichu** [comment]
Actually, this test was very recently touched because it was misbehaving in CI: https://github.com/apple/swift-package-manager/pull/5851, I might be chasing my tail here and this is completely unrelated to the other failures. Let's disable that test again for the purpose of this PR.

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
As far as I can see, all commands in this build are using the same path `/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib`, so I do not understand how we are able to compile SwiftPM's own tests, but fail to build tests from the inferior SwiftPM. It seems like there has to be a proper `XCTest.swiftmodule` at that location in order for anything to build.

**Comment by neonichu** [comment]
Converting this one to draft for now since it's unclear what could be broken, it seems like the compiler flags SwiftPM generates are as expected.

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
Finally hit the failure 🥳 

As expected, we're indeed loading the PCM instead of the XCTest Swift module:

```
remark: loaded module at /Users/ec2-user/jenkins/workspace/swift-package-manager-PR-macos-smoke-test/branch-main/build/buildbot_incremental/swiftpm-macosx-x86_64/x86_64-apple-macosx/release/115J8QW8CNTI9/XCTest-3K270VIN2QZ63.pcm
```

This is despite SwiftPM passing a correct search path for the location of `XCTest.swiftmodule` inside Xcode:

```
-I /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib
```

I'm not sure SwiftPM could be causing this, so likely a compiler issue?

**Comment by neonichu** [comment]
Does feel weird that we're using a shared module cache here when normally we'd be using one inside of `/private/var/folders/pf/p5g2vb2j0yx1x6vlmxdppc700000gn/T/TemporaryDirectory.umEqf0/Foo/.build/`, the build directory of the specific package under test. Not sure if using a shared cache could be part of the issue?

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test windows

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
We're at >20 runs since the last observation of the failure, I wonder if anything has changed under us that resolved it? 🤔

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
OK, running one more pass, but if this one also succeeds, I'm going to remove the changes from add36cec8c9488b4bd8a79acc98c9f9da19c70df and see if the seemingly 100% pass rate is related to the additional logging or if some underlying issue was fixed.

**Comment by neonichu** [comment]
This macOS failure looks unrelated: 

```
/Users/ec2-user/jenkins/workspace/swift-package-manager-PR-macos-smoke-test/branch-main/swift-driver/Sources/SwiftDriver/Jobs/Planning.swift:200:31: error: variable binding in a condition requires an initializer\n    guard let dependencyGraph else {\n                              ^\nninja: build stopped: subcommand failed.\n'
Ninja invocation failed: 
```

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
```
[951/1087] Compiling SwiftDriver GeneratePCHJob.swift
/Users/ec2-user/jenkins/workspace/swift-package-manager-with-xcode-self-hosted-PR-osx/branch-main/swiftpm/.build/checkouts/swift-driver/Sources/SwiftDriver/Jobs/Planning.swift:200:31: error: variable binding in a condition requires an initializer
    guard let dependencyGraph else {
                              ^
```

Hmmm, not sure what this is about -- @artemcm any ideas?

**Comment by artemcm** [comment]
@swift-ci please smoke test macOS

**Comment by artemcm** [comment]
> ```
> [951/1087] Compiling SwiftDriver GeneratePCHJob.swift
> /Users/ec2-user/jenkins/workspace/swift-package-manager-with-xcode-self-hosted-PR-osx/branch-main/swiftpm/.build/checkouts/swift-driver/Sources/SwiftDriver/Jobs/Planning.swift:200:31: error: variable binding in a condition requires an initializer
>     guard let dependencyGraph else {
>                               ^
> ```
> 
> 
>      
>   
> 
> Hmmm, not sure what this is about -- @artemcm any ideas?

My bad. Fixed this here: https://github.com/apple/swift-driver/pull/1233.

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
3 successful runs so far, I think we should do ~10 before making any further determination.

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
We are at 9 runs, so one more. Since we haven't seen the error again, it seems like it was stemming from some underlying tools failure rather than anything in SwiftPM itself.

**Comment by neonichu** [comment]
@swift-ci please smoke test macOS

**Comment by neonichu** [comment]
OK, this passed again. This should be sufficient signal to reenable the disabled tests. There's also a fix in here for one test which we need to bring in, as well as some other changes we should land. I'm going to split this PR into a couple individual changes.

**Comment by neonichu** [comment]
Created https://github.com/apple/swift-package-manager/pull/5958 and https://github.com/apple/swift-package-manager/pull/5957 for the other changes that were previously part of this PR.
