### PR TITLE
SR-1005: Ground work for building against Foundation

### PR DESCRIPTION
**Pull request by Bouke**
As requested by Daniel on slack, I've split the ground work of the Foundation PRs into a separate PR. This replaces the custom String+Linux by the default Foundation implementation. However there is a build issue on Linux that prevents this PR from being merged.

### CODE REVIEW

**Comment by ddunbar** [comment]
I don't think we want any of the changes that *use* Foundation in this PR, they won't work without the other bootstrap changes?

File: Utilities/bootstrap [hunk 1]
```diff
@@ -627,19 +627,25 @@ def main():
...
         cmd.extend(["-Xswiftc", "-I{}".format(core_foundation_path)])
 
+    if args.xctest_path:
+        # Tell the linker where to look for XCTest, but autolinking
+        # knows to pass -lXCTest.
+        cmd.extend(["-Xlinker", "-L", "-Xlinker", args.xctest_path])
+        # Add an RPATH, so that the tests can be run directly.
+        cmd.extend(["-Xlinker", "-rpath", "-Xlinker", args.xctest_path])
+        cmd.extend(["-Xswiftc", "-I{}".format(args.xctest_path)])
+
```
Comment (ddunbar) [inline Utilities/bootstrap]: We need the same logic here to be replicated in the code that builds up the command line for the stage1 build. Otherwise only the stage2 build is going to have access to Foundation and friends.

**Comment by Bouke** [comment]
I dropped the commit where Foundation was actually used.

File: Utilities/bootstrap [hunk 2]
```diff
@@ -542,7 +542,7 @@ def main():
         args.swiftc_path = get_swiftc_path()
 
     build_actions = set(args.build_actions)
-            
+
```
Comment (ddunbar) [inline Utilities/bootstrap]: Please drop spurious whitespace changes, if possible. Not a biggie, but makes for more readable diffs.

**Comment by ddunbar** [comment]
@swift-ci please test

**Comment by Bouke** [comment]
Updated to not pass incorrect arguments for OSX.

**Comment by ddunbar** [comment]
@swift-ci please test

**Comment by Bouke** [comment]
The build failure on Linux doesn't appear to be related to this PR:

    /home/buildnode/jenkins/workspace/swift-package-manager-PR-Linux/swift/validation-test/compiler_crashers/28279-swift-archetypebuilder-potentialarchetype-getnestedtype.swift:9:1: error: statement cannot begin with a closure expression

It builds fine on my Ubuntu 15.10 VM.

**Comment by aciidb0mb3r** [comment]
@swift-ci please test linux
