### ISSUE TITLE
Unable to cross compile `Failed to parse target info (malformed).`

### ISSUE THREAD

**Issue by colemancda** [apple/swift-package-manager#5835]
### Description

I've created [scripts to cross compile to Linux Armv7](https://github.com/colemancda/swift-armv7). While this is currently working on Linux with the official 5.7 release, on macOS (with the downloaded toolchain) the same JSON is unable to cross compile, throwing errors when parsing the `destinaton.json` provide to `swift build --destination destination.json`.

```
TSCUtility/Triple.swift:209: Fatal error: Failed to parse target info (malformed).
```

```
{
   "version":1,
   "sdk":"/Users/coleman/Developer/swift-armv7/build/swift-5.7-RELEASE-armv7-debian11.xctoolchain",
   "toolchain-bin-dir":"/Users/coleman/Developer/swift-armv7/build/swift-5.7-RELEASE-armv7-debian11.xctoolchain/usr/bin",
   "target":"armv7-unknown-linux-gnueabihf",
   "dynamic-library-extension":"so",
   "extra-cc-flags":[
      "-fPIC"
   ],
   "extra-swiftc-flags":[
      "-target", "armv7-unknown-linux-gnueabihf",
      "-use-ld=lld",
      "-tools-directory", "/Users/coleman/Developer/swift-armv7/build/swift-5.7-RELEASE-armv7-debian11.xctoolchain/usr/bin",
      "-Xlinker", "-rpath", "-Xlinker", "/usr/lib/swift/linux",
      "-Xlinker", "-rpath", "-Xlinker", "/usr/lib/swift/linux/armv7",
      "-Xlinker", "-L/Users/coleman/Developer/swift-armv7/build/swift-5.7-RELEASE-armv7-debian11.xctoolchain",
      "-Xlinker", "-L/Users/coleman/Developer/swift-armv7/build/swift-5.7-RELEASE-armv7-debian11.xctoolchain/lib",
      "-Xlinker", "-L/Users/coleman/Developer/swift-armv7/build/swift-5.7-RELEASE-armv7-debian11.xctoolchain/usr/lib",
      "-Xlinker", "-L/Users/coleman/Developer/swift-armv7/build/swift-5.7-RELEASE-armv7-debian11.xctoolchain/usr/lib/swift",
      "-Xlinker", "-L/Users/coleman/Developer/swift-armv7/build/swift-5.7-RELEASE-armv7-debian11.xctoolchain/usr/lib/swift/linux",
      "-Xlinker", "-L/Users/coleman/Developer/swift-armv7/build/swift-5.7-RELEASE-armv7-debian11.xctoolchain/usr/lib/swift/linux/armv7",
      "-Xlinker", "--build-id=sha1",
      "-I/Users/coleman/Developer/swift-armv7/build/swift-5.7-RELEASE-armv7-debian11.xctoolchain/usr/include",
      "-I/Users/coleman/Developer/swift-armv7/build/swift-5.7-RELEASE-armv7-debian11.xctoolchain/usr/lib/swift",
      "-resource-dir", "/Users/coleman/Developer/swift-armv7/build/swift-5.7-RELEASE-armv7-debian11.xctoolchain/usr/lib/swift",
      "-Xclang-linker", "-B/Users/coleman/Developer/swift-armv7/build/swift-5.7-RELEASE-armv7-debian11.xctoolchain/usr/lib",
      "-sdk", "/Users/coleman/Developer/swift-armv7/build/swift-5.7-RELEASE-armv7-debian11.xctoolchain"
   ],
   "extra-cpp-flags":[
      "-lstdc++"
   ]
}

```

### Expected behavior

Cross compiling from macOS should work the same as Linux. `armv7-unknown-linux-gnueabihf` should be a valid triple.

### Actual behavior

The same scripts and destination.json file work on Linux and fail on macOS.

### Steps to reproduce

1. `git clone --branch feature/xctoolchain https://github.com/colemancda/swift-armv7.git`
2. `cd swift-armv7`
3. `git checkout a5d7a33076fe69e63da75f9d0abd78629ebce097` 
4. `generate-xcode-toolchain.sh`

### Swift Package Manager version/commit hash

swift-5.7-RELEASE

### Swift & OS version (output of `swift --version && uname -a`)

```
swift-driver version: 1.62.8 Apple Swift version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50)
Target: arm64-apple-macosx12.0
Darwin Apple-MacBook-Pro.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 arm64
```

**Comment by colemancda** [comment]
This simpler file I made by hand also fails 

`swift build --destination '/Users/coleman/Developer/swift-armv7/build/armv7-unknown-linux-gnueabihf-toolchain.json'`

```
{
   "version": 1,
   "sdk": "/Users/coleman/Developer/swift-armv7/bullseye-armv7",
   "toolchain-bin-dir": "/Users/coleman/Developer/swift-armv7/build/swift-5.7-RELEASE-armv7-debian11.xctoolchain/usr/bin",
   "target": "armv7-unknown-linux-gnueabihf",
   "extra-cc-flags": [
       "-fPIC"
   ],
   "extra-swiftc-flags": [
       "-use-ld=lld",
       "-tools-directory", "/Users/coleman/Developer/swift-armv7/build/swift-5.7-RELEASE-armv7-debian11.xctoolchain/usr/bin",
       "-sdk", "/Users/coleman/Developer/swift-armv7/bullseye-armv7"
   ],
   "extra-cpp-flags": [
       "-lstdc++"
   ]
}
```

**Comment by colemancda** [comment]
Event his is failing, so its possibly not the JSON 

```
{
   "version": 1,
   "sdk": "/Users/coleman/Developer/swift-armv7/bullseye-armv7",
   "toolchain-bin-dir": "/Users/coleman/Developer/swift-armv7/build/swift-5.7-RELEASE-armv7-debian11.xctoolchain/usr/bin",
   "target": "x86_64-unknown-linux-gnu",
   "extra-cc-flags": [
       "-fPIC"
   ],
   "extra-swiftc-flags": [
   ],
   "extra-cpp-flags": [
       "-lstdc++"
   ]
}
```
