### PR TITLE
Add a customized GitRepositoryError and funnel all Git operations through a method that throws one of those if an operation fails.

### PR DESCRIPTION
**Pull request by abertelrud**
This makes sure that Git failures clients can distinguish from other Process errors (so failure handling can be customized), and that they all have a location.  At present the location for an error during a cloning operation is the remote URL, while the operation for an operation on a local clone is the path of the local clone.  We might want to extend this in the future so that local clones also keep track of the URL, but this will require the GitRepository to keep a copy of the associated RepositorySpecifier of its origin remote.  This would in turn require a change to the Repository protocol so that all methods take a RepositorySpecificier, and it would require changes to all the clients.  So that should be a separate PR.

### CODE REVIEW

**Comment by abertelrud** [comment]
@swift-ci please smoke test

**Comment by abertelrud** [comment]
Looks like the CI is currently having unrelated issues: `java.io.IOException: Read-only file system`

**Comment by abertelrud** [comment]
The macOS test failure seems to be because of not using a new enough `swift-tools-support-core`.

**Comment by abertelrud** [comment]
@swift-c please smoke test

**Comment by abertelrud** [comment]
@swift-ci please smoke test

**Comment by abertelrud** [comment]
The Linux failures seem to have been due to the SwiftDriver CMake problem.  Trying again.

**Comment by abertelrud** [comment]
@swift-ci please smoke test

**Review by neonichu — APPROVED** [review]

**Comment by abertelrud** [comment]
@swift-ci please smoke test

**Comment by abertelrud** [comment]
The test failures are different this time but still completely unrelated to this PR:
```12:09:09 In file included from /home/buildnode/jenkins/workspace/swift-package-manager-Linux-smoke-test/branch-main/swift/stdlib/public/runtime/AnyHashableSupport.cpp:19:
12:09:09 
/home/buildnode/jenkins/workspace/swift-package-manager-Linux-smoke-test/branch-main/swift/include/swift/Runtime/Concurrent.h:671:9: error: use of undeclared identifier 'swift_runtime_unreachable'; did you mean 'swift_unreachable'?
12:09:09         swift_runtime_unreachable("unknown index size");
```

**Comment by abertelrud** [comment]
The test failure is the same as in https://github.com/apple/swift-package-manager/pull/2970

**Comment by abertelrud** [comment]
@swift-ci please smoke test
