### PR TITLE
Improve handling of minimum deployment target

### PR DESCRIPTION
**Pull request by neonichu**
We have a bit of a muddled deployment target situation in 5.2:
- anything declared by SwiftPM's own manifest defaulted to macOS 10.10,
but the toolchain doesn't actually work on macOS < 10.15 anymore
- libPackageDescription was built with minimum deployment target of
10.15, but we were explicitly compiling the manifest for 10.10 minimum
- support for running tests on macOS is aligned with Xcode (so 10.15
minimum), but we were not enforcing that

This change makes it more consistent for 5.3:
- declare a 10.15 minimum in the manifest
- build manifests without deployment target, defaulting to the host
- always build tests for macOS with a minimum deployment target of 10.15

rdar://problem/62121806

### CODE REVIEW

File: Sources/XCBuildSupport/PIFBuilder.swift [hunk 1]
```diff
@@ -255,7 +255,7 @@ final class PackagePIFProjectBuilder: PIFProjectBuilder {
         settings[.SDKROOT] = "auto"
         settings[.SDK_VARIANT] = "auto"
         settings[.SKIP_INSTALL] = "YES"
-        let firstTarget = package.targets.first?.underlyingTarget
+        let firstTarget = package.targets.first(where: { $0.type != .test })?.underlyingTarget ?? package.targets.first?.underlyingTarget
```
Comment (neonichu) [inline Sources/XCBuildSupport/PIFBuilder.swift:258]: This ensures we're not using a test target as representative for the package if there are other targets.

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by SDGGiesbrecht** [comment]
Is there some way to do this without restricting client packages who want to continue using it conditionally with `#available`?

**Comment by neonichu** [comment]
@SDGGiesbrecht you're specifically talking about the change to SwiftPM's package manifest and clients of libSwiftPM, right?

**Comment by SDGGiesbrecht** [comment]
Yes. It’s just the `platforms: [.macOS("10.15")]` entry in the manifest that causes issues.

**Comment by SDGGiesbrecht** [comment]
...and only when pulled in as a package dependency. Basing it on an environment variable like `SWIFTPM_LLBUILD_FWK` would be fine if it needs to be there for the toolchain build.

**Comment by neonichu** [comment]
I think that sounds reasonable to me.

File: Sources/PackageLoading/PackageBuilder.swift [hunk 2]
```diff
@@ -836,19 +836,26 @@ public final class PackageBuilder {
...
 
         var supportedPlatforms: [SupportedPlatform] = []
 
         /// Add each declared platform to the supported platforms list.
         for platform in manifest.platforms {
+            let declaredPlatform = platformRegistry.platformByName[platform.platformName]!
+            var version = PlatformVersion(platform.version)
+
+            // macOS tests have a higher minimum deployment target
+            if declaredPlatform == Platform.macOS && isTest && version < PlatformVersion("10.15") {
```
Comment (jakepetroules) [inline Sources/PackageLoading/PackageBuilder.swift:852]: This isn't future proof. What we actually want here is whatever the deployment target of XCTest is. What I would suggest is to read the LC_BUILD_VERSION load command from the XCTest framework, and use that.

I don't remember if we have any Mach-O parsing utilities in SwiftPM or TSC, but if not, you can read it using vtool and parse the output.

```
$ xcrun vtool -show-build $(xcrun --sdk macosx --show-sdk-platform-path)/Developer/Library/Frameworks/XCTest.framework/XCTest
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks/XCTest.framework/XCTest:
Load command 8
      cmd LC_BUILD_VERSION
  cmdsize 32
 platform MACOS
    minos 10.14
      sdk 10.15.4
   ntools 1
     tool LD
  version 556.6
Load command 9
      cmd LC_BUILD_VERSION
  cmdsize 32
 platform MACCATALYST
    minos 13.1
      sdk 13.4
   ntools 1
     tool LD
  version 556.6

```

Just grab the value for the first line starting with "minos".

File: Package.swift [hunk 3]
```diff
@@ -14,6 +14,9 @@ import PackageDescription
 
 let package = Package(
     name: "SwiftPM",
+    platforms: [
+        .macOS("10.15"),
```
Comment (aciidb0mb3r) [inline Package.swift:18]: nit: use .v10_15

We'll also need to add this in the CMake configuration

File: Sources/PackageLoading/PackageBuilder.swift [hunk 4]
```diff
@@ -836,19 +836,26 @@ public final class PackageBuilder {
...
+                version = PlatformVersion("10.15")
```
Comment (aciidb0mb3r) [inline Sources/PackageLoading/PackageBuilder.swift:853]: Can you declare this as a constant in order to avoid potential typos:

```swift
extension PlatformVersion {
    static let v10_15: PlatformVersion = PlatformVersion("10.15")
}
```

File: Sources/PackageLoading/PackageBuilder.swift [hunk 5]
```diff
@@ -836,19 +836,26 @@ public final class PackageBuilder {
...
         }
 
         var supportedPlatforms: [SupportedPlatform] = []
 
         /// Add each declared platform to the supported platforms list.
         for platform in manifest.platforms {
+            let declaredPlatform = platformRegistry.platformByName[platform.platformName]!
+            var version = PlatformVersion(platform.version)
+
+            // macOS tests have a higher minimum deployment target
```
Comment (aciidb0mb3r) [inline Sources/PackageLoading/PackageBuilder.swift:851]: Can you a more detailed note on why we have to special case here?

File: Sources/XCBuildSupport/PIFBuilder.swift (hunk 1 above)
Comment (aciidb0mb3r) [reply Sources/XCBuildSupport/PIFBuilder.swift:258]: Hmm, this doesn't seem correct. I think we should set deployment target at target-level now?

File: Sources/PackageLoading/PackageBuilder.swift [hunk 6]
```diff
@@ -862,19 +869,26 @@ public final class PackageBuilder {
...
             supportedPlatforms.append(supportedPlatform)
         }
 
-        _platforms = supportedPlatforms
-        return _platforms!
+        _platforms[isTest] = supportedPlatforms
+        return supportedPlatforms
     }
-    private var _platforms: [SupportedPlatform]? = nil
+    private var _platforms = [Bool:[SupportedPlatform]]()
```
Comment (aciidb0mb3r) [inline Sources/PackageLoading/PackageBuilder.swift:891]: Can you add a doc comment here explaining what the key of the dictionary is.

**Comment by neonichu** [comment]
> How about we leave it at a fixed 10.15 for now?

I think we can actually do the same thing you suggested for XCTest and use the deployment target of libPackageDescription.

**Comment by neonichu** [comment]
> error: the library 'SKSwiftPMWorkspace' requires macos 10.10, but depends on the product 'SwiftPM-auto' which requires macos 10.15; consider changing the library 'SKSwiftPMWorkspace' to require macos 10.15 or later, or the product 'SwiftPM-auto' to require macos 10.10 or earlier.

Another reason to only specify the deployment target when we're building SwiftPM for deployment in a toolchain.

File: Sources/XCBuildSupport/PIFBuilder.swift (hunk 1 above)
Comment (neonichu) [reply Sources/XCBuildSupport/PIFBuilder.swift:258]: I think we did this originally because products have no deployment target in the model and the deployment target was the same for all targets anyway. I'm not sure if it is worth taking the full complexity of validating deployment targets for products based on their underlying targets now.

File: Sources/PackageLoading/PackageBuilder.swift (hunk 5 above)
Comment (jakepetroules) [reply Sources/PackageLoading/PackageBuilder.swift:851]: > > How about we leave it at a fixed 10.15 for now?
> 
> I think we can actually do the same thing you suggested for XCTest and use the deployment target of libPackageDescription.

Hmm, yeah, that seems like a good idea!

**Comment by jakepetroules** [comment]
> > How about we leave it at a fixed 10.15 for now?
> 
> I think we can actually do the same thing you suggested for XCTest and use the deployment target of libPackageDescription.

Hmm, yeah, that seems like a good idea!

**Comment by neonichu** [comment]
@swift-ci please smoke test

File: Sources/XCBuildSupport/PIFBuilder.swift (hunk 1 above)
Comment (aciidb0mb3r) [reply Sources/XCBuildSupport/PIFBuilder.swift:258]: but this won't set the right deployment for test targets, right?

File: Utilities/bootstrap [hunk 7]
```diff
@@ -25,6 +25,8 @@ import shutil
 import subprocess
 from helpers import note, error, symlink_force, mkdir_p, call, call_output
 
+macos_deployment_target = '10.15'
```
Comment (aciidb0mb3r) [inline Utilities/bootstrap:28]: nit: prefix with g_

File: Sources/PackageLoading/PackageBuilder.swift [hunk 8]
```diff
@@ -1189,3 +1213,26 @@ extension Sources {
...
+    #if os(macOS)
+    do {
+        let runResult = try Process.popen(arguments: ["xcrun", "--sdk", "macosx", "--show-sdk-platform-path"])
+        let sdkPath = AbsolutePath(try runResult.utf8Output().spm_chuzzle() ?? "")
+        let xcTestPath = sdkPath.appending(RelativePath("Developer/Library/Frameworks/XCTest.framework/XCTest"))
+
+        if let version = try computeMinimumDeploymentTarget(of: xcTestPath) {
+            return version
+        }
+    } catch { } // we do not treat this a fatal and instead use the fallback minimum deployment target
```
Comment (aciidb0mb3r) [inline Sources/PackageLoading/PackageBuilder.swift:1234]: should we emit a warning here?

Comment (neonichu) [reply Sources/PackageLoading/PackageBuilder.swift:1234]: maybe?

File: Sources/PackageLoading/PackageBuilder.swift [hunk 9]
```diff
@@ -835,20 +835,36 @@ public final class PackageBuilder {
...
 
+    // When building tests on macOS, we are matching the minimum deployment target of the XCTest framework.
+    func xcTestMinimumDeploymentTarget() -> PlatformVersion {
+        if let minDeploymentTarget = _xcTestMinimumDeploymentTarget {
+            return minDeploymentTarget
+        }
+        _xcTestMinimumDeploymentTarget = computeXCTestMinimumDeploymentTarget()
+        return _xcTestMinimumDeploymentTarget!
+    }
+    private var _xcTestMinimumDeploymentTarget: PlatformVersion? = nil
```
Comment (aciidb0mb3r) [inline Sources/PackageLoading/PackageBuilder.swift:846]: Can you cache this in a static variable as we run the package builder for each package.

File: Sources/PackageLoading/ManifestLoader.swift [hunk 10]
```diff
@@ -540,14 +541,25 @@ public final class ManifestLoader: ManifestLoaderProtocol {
...
+
+                packageDescriptionPath = packageFrameworkPath.appending(RelativePath("PackageDescription.framework/PackageDescription"))
             } else {
                 cmd += [
                     "-L", runtimePath.pathString,
                     "-lPackageDescription",
                     "-Xlinker", "-rpath", "-Xlinker", runtimePath.pathString
                 ]
+
+                // note: this is not correct for all platforms, but we only actually use it on macOS.
```
Comment (aciidb0mb3r) [inline Sources/PackageLoading/ManifestLoader.swift:553]: maybe rename to `macOSPackageDescriptionPath` then?

File: Sources/PackageLoading/ManifestLoader.swift [hunk 11]
```diff
@@ -540,14 +541,25 @@ public final class ManifestLoader: ManifestLoaderProtocol {
...
+                packageDescriptionPath = runtimePath.appending(RelativePath("libPackageDescription.dylib"))
             }
 
+            // Use the same minimum deployment target as the PackageDescription library (with a fallback of 10.15).
+            #if os(macOS)
+            let version = (try computeMinimumDeploymentTarget(of: packageDescriptionPath))?.versionString ?? "10.15"
```
Comment (aciidb0mb3r) [inline Sources/PackageLoading/ManifestLoader.swift:559]: we should cache the result as this code is executed for each manifest.

File: Package.swift [hunk 12]
```diff
@@ -11,9 +11,21 @@
...
+let macOSPlatform: SupportedPlatform
+if let deploymentTarget = ProcessInfo.processInfo.environment["SWIFTPM_MACOS_DEPLOYMENT_TARGET"] {
+    macOSPlatform = .macOS(deploymentTarget)
+} else {
+    macOSPlatform = .macOS(.v10_10)
+}
 
 let package = Package(
     name: "SwiftPM",
+    platforms: [ macOSPlatform, ],
```
Comment (aciidb0mb3r) [inline Package.swift:28]: nit: `platforms: [macOSPlatform],`

File: Package.swift [hunk 13]
```diff
@@ -11,9 +11,21 @@
...
+import class Foundation.ProcessInfo
+
+// We default to a 10.10 minimum deployment target for clients of libSwiftPM,
+// but allow overriding it when building for a toolchain.
+
+let macOSPlatform: SupportedPlatform
+if let deploymentTarget = ProcessInfo.processInfo.environment["SWIFTPM_MACOS_DEPLOYMENT_TARGET"] {
+    macOSPlatform = .macOS(deploymentTarget)
+} else {
+    macOSPlatform = .macOS(.v10_10)
```
Comment (aciidb0mb3r) [inline Package.swift:23]: Let's just bump to whatever we actually support. We'll need to update sourcekit-lsp. Are you fine with that @benlangmuir?

File: Sources/PackageLoading/PackageBuilder.swift [hunk 14]
```diff
@@ -1189,3 +1213,26 @@ extension Sources {
...
     }
 }
+
+func computeMinimumDeploymentTarget(of binaryPath: AbsolutePath) throws -> PlatformVersion? {
+    let runResult = try Process.popen(arguments: ["xcrun", "vtool", "-show-build", binaryPath.pathString])
+    guard let versionString = try runResult.utf8Output().components(separatedBy: "\n").first(where: { $0.contains("minos") })?.components(separatedBy: " ").last else { return nil }
+    return PlatformVersion(versionString)
+}
+
+private func computeXCTestMinimumDeploymentTarget() -> PlatformVersion {
```
Comment (aciidb0mb3r) [inline Sources/PackageLoading/PackageBuilder.swift:1223]: Actually, I just realized that we shouldn't compute this here because PackageBuilder can run completely in-memory on a fake file system. This value should be input to PackageBuilder from somewhere else (probably via UserToolchain).

File: Package.swift (hunk 13 above)
Comment (benlangmuir) [reply Package.swift:23]: > but the toolchain doesn't actually work on macOS < 10.15 anymore

This is news to me, where was this change discussed?

File: Sources/PackageLoading/PackageBuilder.swift (hunk 14 above)
Comment (jakepetroules) [reply Sources/PackageLoading/PackageBuilder.swift:1223]: Also, nothing about the XCTest logic is macOS-specific, by the way,.

If we need to care about Mac Catalyst/iOS/tvOS/watchOS in this context, then this function should take the platform/SDK as an input.

Comment (neonichu) [reply Sources/PackageLoading/PackageBuilder.swift:1223]: I didn't realise that XCTest has a higher minimum than what we support building for on the other platforms as well, that's why this was done only for macOS. The question is what do we do for watchOS...

File: Sources/XCBuildSupport/PIFBuilder.swift (hunk 1 above)
Comment (neonichu) [reply Sources/XCBuildSupport/PIFBuilder.swift:258]: Yah, that's true, we should special case test targets.

File: Package.swift (hunk 13 above)
Comment (neonichu) [reply Package.swift:23]: Not sure if it was discussed, bu it's the de facto behaviour today, e.g. `libPackageDescription` in the 5.2 toolchain has a 10.15 minimum deployment target. Since 11.4 only supports 10.15+, it seems like the same should be true for the toolchain as well, right?

**Comment by neonichu** [comment]
> /Users/buildnode/jenkins/workspace/swift-package-manager-PR-osx-smoke-test/branch-master/swiftpm/Tests/PackageLoadingTests/PackageBuilderTests.swift:1578: error: -[PackageLoadingTests.PackageBuilderTests testPlatforms] : XCTAssertEqual failed: ("["watchos": "2.0", "ios": "8.0", "macos": "10.15", "android": "0.0", "wasi": "0.0", "tvos": "9.0", "linux": "0.0"]") is not equal to ("["watchos": "2.0", "tvos": "9.0", "ios": "8.0", "linux": "0.0", "android": "0.0", "wasi": "0.0", "macos": "10.14"]")

makes sense, XCTest on CI still has a 10.14 minimum deployment target, the test should be using a dynamic value as well.

File: Sources/PackageLoading/PackageBuilder.swift (hunk 8 above)
Comment (neonichu) [reply Sources/PackageLoading/PackageBuilder.swift:1234]: I think we shouldn't for now. Once we extend this to all platforms as suggested by Jake, we'd always get a warning for watchOS because that code will never succeed there today.

File: Sources/PackageLoading/PackageBuilder.swift (hunk 14 above)
Comment (neonichu) [reply Sources/PackageLoading/PackageBuilder.swift:1223]: I think the answer is actually to change this method to return the oldest supported version if we can't determine one via the XCTest.framework. This way we don't end up with a constant that needs updating.

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
Failure is:

> /home/buildnode/jenkins/workspace/swift-package-manager-self-hosted-Linux-smoke-test/branch-master/swiftpm/Tests/PackageLoadingTests/PackageBuilderTests.swift:1580: error: PackageBuilderTests.testPlatforms : XCTAssertEqual failed: ("["linux": "0.0", "watchos": "2.0", "ios": "8.0", "macos": "10.10", "wasi": "0.0", "tvos": "9.0", "android": "0.0"]") is not equal to ("["android": "0.0", "macos": "10.12", "watchos": "2.0", "linux": "0.0", "wasi": "0.0", "ios": "8.0", "tvos": "9.0"]") -

File: Sources/PackageLoading/PackageBuilder.swift (hunk 8 above)
Comment (abertelrud) [reply Sources/PackageLoading/PackageBuilder.swift:1238]: This could fail for all kinds of reasons, though, such as if I haven't done `xcode-select` properly, etc.  Could it be confusing to silently get the default fallback deployment target in some cases but not others?

**Comment by neonichu** [comment]
@swift-ci please smoke test

File: Sources/PackageLoading/PackageBuilder.swift [hunk 15]
```diff
@@ -835,20 +835,36 @@ public final class PackageBuilder {
         return conditions
     }
 
+    // When building tests on macOS, we are matching the minimum deployment target of the XCTest framework.
+    func xcTestMinimumDeploymentTarget(for platform: PackageModel.Platform) -> PlatformVersion {
+        if let minDeploymentTarget = Self._xcTestMinimumDeploymentTarget[platform] {
+            return minDeploymentTarget
+        }
+        Self._xcTestMinimumDeploymentTarget[platform] = computeXCTestMinimumDeploymentTarget(for: platform)
```
Comment (aciidb0mb3r) [inline Sources/PackageLoading/PackageBuilder.swift:843]: this should be input to PackageBuilder as it's not supposed to have any side effects.

Comment (neonichu) [reply Sources/PackageLoading/PackageBuilder.swift:843]: Ah yah, I missed this before 😢

File: Package.swift (hunk 13 above)
Comment (neonichu) [reply Package.swift:23]: We talked about this offline and decided to keep the current approach (build with 10.15 in the toolchain, but `libSwiftPM` will have 10.10 minimum deployment target)

**Comment by neonichu** [comment]
@swift-ci please smoke test
