### PR TITLE
Allow passing `--triple` alone to select a Swift SDK

### LINKED ISSUE #7330: `--triple` option doesn't take installed Swift SDKs into account
### Description

It's confusing that the existing `--triple` option does look at target triples of installed SDKs and seems to be completely detached from the Swift SDK infrastructure. We should be able to look at the list of installed SDKs and their supported target triples and select the SDK based on that. Probably for multiple Swift SDKs supporting the same target triple we should fail with an error message.

### Expected behavior

`swift build --triple wasm32-unknown-wasi` picks up installed Swift SDK that supports triple.

### Actual behavior

`swift build --triple wasm32-unknown-wasi` doesn't find the installed Swift SDK.

### Steps to reproduce

1. Install a Swift SDK that supports `wasm32-unknown-wasi` target triple
2. Change current directory to the root directory of a package that you'd like to build.
3. Run `swift build --triple wasm32-unknown-wasi`

### Swift Package Manager version/commit hash

Swift Package Manager - Swift 5.11.0-dev

### Swift & OS version (output of `swift --version ; uname -a`)

Swift version 5.11-dev (LLVM 87ace14daa2139a, Swift 8bb684628593220)
Target: aarch64-unknown-linux-gnu

### PR DESCRIPTION
**Pull request by finagolfin**
Simply aliases it to `--swift-sdk triple` and finally adds a help string for the flag, fixes #7330. I checked to make sure the `--swift-sdk` error strings still make sense and they do, because they use the generic word "query" anyway.

This passed all tests locally on macOS except for one:
```
Test Case '-[PackageModelTests.SwiftSDKBundleTests testTargetSDKDerivation]' started.
/Users/finagolfin/swift/swiftpm/Tests/PackageModelTests/SwiftSDKBundleTests.swift:537: error: -[PackageModelTests.SwiftSDKBundleTests testTargetSDKDerivation] : failed: caught error: "No Swift SDK found matching query `aarch64-unknown-linux-gnu` and host triple `arm64-apple-macosx14.0`. Use the `swift sdk list` command to see available Swift SDKs."
Test Case '-[PackageModelTests.SwiftSDKBundleTests testTargetSDKDerivation]' failed (0.121 seconds).
```
That test was added in #8034, in support of a strange config where you could use the host SDK but override the triple, ie ignoring the installed bundles. Supporting that is not going to work with selecting a triple from the installed bundles as requested in #7330, unless we check if no bundles are installed, and only then default to the host SDK override logic. That will be weird for the user, where the host SDK override is applied only _if_ no bundles happen to be installed.

Instead, I think we should just throw out that [host toolset override logic](https://github.com/swiftlang/swift-package-manager/pull/8034/changes#diff-a434883777befb0b6ef138f44a098a3d63d3b9dc59b521e16e2c5b3a6163117fR706), and [move this line](https://github.com/swiftlang/swift-package-manager/pull/8034/changes#diff-a434883777befb0b6ef138f44a098a3d63d3b9dc59b521e16e2c5b3a6163117fR704) to only apply to [the now somewhat-deprecated destination config files](https://github.com/swiftlang/swift-package-manager/blob/645158ee5da3319cfaf8b1ad03e4fff7c840a57e/Sources/PackageModel/SwiftSDKs/SwiftSDK.swift#L766).

This `--triple` flag was introduced in #2604 to really [only apply to destination files at the time](https://github.com/swiftlang/swift-package-manager/pull/2604/changes#diff-8d396837a0426c26967e471b82d8f2eaf31f9a7ae2e03308300799edbac4bd18R809), and probably never worked well for the host destination it was also applied to then. It probably doesn't work very well for host SDK overrides today, unless you really know what you're doing.

Better to only apply this `--triple` flag to the old destination files, which it was first introduced for, and as a selector for Swift SDK bundles, as I do in this pull, throwing out the old host override logic and closing #8716 as unsupported. I think we have a free hand here, since this flag was never documented till now. I'll adjust that test and add a couple more depending on what's decided.

Let me know what you think, @jakepetroules, @kateinoigakukun, and @MaxDesiatov.

### CODE REVIEW

File: Sources/PackageModel/SwiftSDKs/SwiftSDK.swift [hunk 1]
```diff
@@ -784,10 +784,16 @@ public struct SwiftSDK: Equatable {
...
+        } else if swiftSDKSelector != nil || customCompileTriple != nil {
             do {
                 var ID: String
-                (ID, swiftSDK) = try store.selectBundle(matching: swiftSDKSelector, hostTriple: hostTriple, targetTriple: customCompileTriple)
+                if let swiftSDKSelector {
+                    (ID, swiftSDK) = try store.selectBundle(matching: swiftSDKSelector, hostTriple: hostTriple, targetTriple: customCompileTriple)
+                } else if let customCompileTriple {
+                    (ID, swiftSDK) = try store.selectBundle(matching: customCompileTriple.tripleString, hostTriple: hostTriple)
+                } else {
+                    fatalError("Neither an SDK nor a triple matched somehow.")
```
Comment (finagolfin) [inline Sources/PackageModel/SwiftSDKs/SwiftSDK.swift:795]: This should never hit, but just putting it in as a guard rail.

**Comment by kateinoigakukun** [comment]
I'm not 100% confident that it doesn't break existing `--triple` usage, but I don't see any valid `--triple` usage except for the legacy `--destination` and Darwin triples, which should be handled by `defaultSwiftSDK` path. So I think it's relatively safe to land.

But specifying `--triple` alone works only when a user installs a single Swift SDK supporting the triple, so I think the recommended canonical form for specifying a specific SDK would remain `--triple <triple> --swift-sdk <sdk-id>`, so I'm worried that adding this support might confuse users.

**Comment by finagolfin** [comment]
> But specifying --triple alone works only when a user installs a single Swift SDK supporting the triple, so I think the recommended canonical form for specifying a specific SDK would remain --triple <triple> --swift-sdk <sdk-id>, so I'm worried that adding this support might confuse users.

Yep, this pull merely implements a shorter form for when only a single SDK includes that triple, and if you happen to have multiple SDKs installed that contain the same triple, it now gives you a nice error about what to do, #9937. You can try that out for yourself with the current trunk snapshot toolchain by passing in `--swift-sdk triple` with multiple bundles installed, and this pull just aliases to that. 🙂

**Comment by jakepetroules** [comment]
> so I'm worried that adding this support might confuse users.

I think this is a reasonable argument -- it trains people to use something that may just break as soon as they install another SDK, which makes things feel unstable.

**Comment by finagolfin** [comment]
> I think this is a reasonable argument -- it trains people to use something that may just break as soon as they install another SDK, which makes things feel unstable.

Unfortunately, that is what _all_ [our](https://www.swift.org/documentation/articles/swift-sdk-for-android-getting-started.html) doc [does right now](https://www.swift.org/documentation/articles/static-linux-getting-started.html), just with the `--swift-sdk <triple>` flag  atm, so this flag would change nothing in that regard.

Now that specifying both the SDK _and_ the triple works with #9955, which we need to get into 6.3, #9998, I will update that doc to tell people to use both flags, then this could just remain a shortcut for those who know what they're doing. I'll try to get the [compiler/SDK version checking](https://forums.swift.org/t/stricter-searching-for-swift-sdks-when-building/86011) in for 6.4, so that will take away the main source of problems, and allow people to use this flag alone.

**Comment by finagolfin** [comment]
Been a couple months, following up on this simple alias to address the linked issue.

@MaxDesiatov, do you think we should no longer add this option, as you asked for in that issue a couple years ago?
