### PR TITLE
[5.5] New disable automatic resolution alias

### PR DESCRIPTION
**Pull request by neonichu**
5.5 cherry-pick of #3706

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Review by abertelrud — APPROVED** [review]

**Comment by neonichu** [comment]
>/Users/buildnode/jenkins/workspace/swift-package-manager-with-xcode-self-hosted-PR-osx/branch-release/5.5/swiftpm/IntegrationTests/Tests/IntegrationTests/XCBuildTests.swift:228: error: -[IntegrationTests.XCBuildTests testLibraryProductsAndTargets] : failed - Command failed with exit code: terminated(code: 1) - command: >/Users/buildnode/jenkins/workspace/swift-package-manager-with-xcode-self-hosted-PR-osx/branch-release/5.5/swiftpm/.build/x86_64-apple-macosx/debug/swift-build --package-path /var/folders/_8/79jmzf2142z2xydc_01btlx00000gn/T/XCBuild_Libraries.lVmDn3/Foo --build-system xcode --target FooLib

Looks like we need to backport the workaround in the integration test suite to 5.5

**Review by abertelrud — APPROVED** [review]

**Comment by neonichu** [comment]
I think instead of backporting the workaround, I'll implement an actual solution since we should fix the incompatibility with newer XCBuilds in a 5.5.x release if possible.

**Comment by abertelrud** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
Failing test in self-hosted is being addressed separately and isn't required to merge this as we are running the full tests for the 5.5 branch.
