### PR TITLE
Do not generate a build parameters file if a custom one has been passed

### PR DESCRIPTION
**Pull request by neonichu**
This already works, because it seems like the second `--buildParametersFile` option wins when invoking `xcbuild`, but it seems better to make this more explicit and more clean to not generate a file if the expectation is that it won't be used.

### CODE REVIEW

**Comment by neonichu** [comment]
Seeing the same test failure as in https://github.com/apple/swift-package-manager/pull/3695

> 15:10:49 Test Case 'APIDiffTests.testCheckVendedModulesOnly' started at 2021-08-27 22:09:39.720
> 15:10:49 
/home/buildnode/jenkins/workspace/swift-package-manager-self-hosted-Linux-smoke-test/branch-main/swiftpm/Tests/CommandsTests/APIDiffTests.swift:144: error: APIDiffTests.testCheckVendedModulesOnly : XCTAssertTrue failed - 
> 15:10:49 Test Case 'APIDiffTests.testCheckVendedModulesOnly' failed (14.045 seconds)

**Review by tomerd — APPROVED** [review]

**Review by abertelrud — APPROVED** [review]

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
Looks as if this wasn't just flaky, `APIDiffTests.testCheckVendedModulesOnly` continues to fail on Linux.

**Comment by tomerd** [comment]
@swift-ci smoke test
