### PR TITLE
Replace custom path type with URL in plugin API

### PR DESCRIPTION
**Pull request by neonichu**
Plugins introduced their own custom path type which doesn't have Windows support, causing several issues with plugins on Windows. We should rectify this situation by using Foundation's URL type instead which already works fine on Windows.

rdar://117230149

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
Two things to point out:
- this introduces a bunch of deprecation warnings for the code in `PackagePlugin` itself since we still need to create paths for backwards compatibility. I am not sure how to avoid these
- since `URL` is now part of the public interface of `PackagePlugin`, we can no longer use implementation-only imports for Foundation

**Comment by neonichu** [comment]
I will look into adding a few new test cases which exercise the new APIs instead of the old ones.

**Comment by neonichu** [comment]
I'm actually a bit surprised that the test suite passes, I seem to be able to see problems with rather trivial manual testing...

**Comment by neonichu** [comment]
> /Users/neonacho/Projects/public/swift-package-manager/Fixtures/Miscellaneous/Plugins/MySourceGenPlugin/.build/plugins/cache/MySourceGenPrebuildPlugin

Ah fun, turns out if you ever build using `bootstrap`, that plugin library will be preferred for running plugins, so what happened was that my SwiftPM was using URLs but the plugin was using an old library which just led to kinda broken paths on the plugin side.

**Comment by neonichu** [comment]
Added a test now which exercises both build tool and prebuild APIs using URLs. This required bumping our version to 5.11 so that the new APIs can be used in the example.

I think two tasks remain for this PR:
- change the deprecation of `Path` such that we can avoid deprecations in our own code (or at least minimize them)
- introduce some kind of versioning for the plugin API library to avoid the same confusion I had with mixing and matching incompatible versions. This should mostly impact development, but it's still worthwhile to handle

File: Sources/PackagePlugin/PluginMessages.swift [hunk 1]
```diff
@@ -263,17 +265,18 @@ enum PluginToHostMessage: Codable {
...
-    case defineBuildCommand(configuration: CommandConfiguration, inputFiles: [String], outputFiles: [String])
-    
+    case defineBuildCommand(configuration: CommandConfiguration, inputFiles: [URL], outputFiles: [URL])
+
     /// The plugin defines a prebuild command.
-    case definePrebuildCommand(configuration: CommandConfiguration, outputFilesDirectory: String)
+    case definePrebuildCommand(configuration: CommandConfiguration, outputFilesDirectory: URL)
     
         struct CommandConfiguration: Codable {
+            var version = 2
```
Comment (neonichu) [inline Sources/PackagePlugin/PluginMessages.swift:274]: Used this as a simple way to "version" the library. This allows us to detect cases where an old plugin library is being used with a newer SwiftPM which would otherwise silently exhibit broken behavior.

**Comment by neonichu** [comment]
I think this should be ready now. There are still a handful of deprecation warnings that I am not certain how to resolve.

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
@swift-ci please test package compatibility

**Comment by neonichu** [comment]
@swift-ci please test windows

**Review by MaxDesiatov — APPROVED** [review]

**Comment by neonichu** [comment]
Hm, looks like on Linux, we don't see the "Applying" messages for plugins?

**Comment by neonichu** [comment]
```
duplicate symbol '_async_MainTu' in:
    /Users/ec2-user/jenkins/workspace/swift-package-manager-with-xcode-self-hosted-PR-osx/branch-main/swiftpm/.build/x86_64-apple-macosx/debug/swift_package.build/Entrypoint.swift.o
    /Users/ec2-user/jenkins/workspace/swift-package-manager-with-xcode-self-hosted-PR-osx/branch-main/swiftpm/.build/x86_64-apple-macosx/debug/swift_test.build/Entrypoint.swift.o
duplicate symbol '_async_Main' in:
    /Users/ec2-user/jenkins/workspace/swift-package-manager-with-xcode-self-hosted-PR-osx/branch-main/swiftpm/.build/x86_64-apple-macosx/debug/swift_package.build/Entrypoint.swift.o
    /Users/ec2-user/jenkins/workspace/swift-package-manager-with-xcode-self-hosted-PR-osx/branch-main/swiftpm/.build/x86_64-apple-macosx/debug/swift_test.build/Entrypoint.swift.o
ld: 2 duplicate symbols for architecture x86_64
[174/175] Linking SwiftPMPackageTests
error: fatalError
```

Yah, I'm seeing this locally, too. It seems like we have accidentally created a dependency on 5.10 compilers here which hide the async main symbol.

**Comment by MaxDesiatov** [comment]
I'm puzzled why this error didn't surface previously on CI when testing PRs that introduced this async entrypoint in the first place. Are reverts to those entrypoints the only available fix?

**Comment by MaxDesiatov** [comment]
AFAIU the error wasn't independently reproducible with any of the `async` entrypoint PRs tested separately, and that's how they were merged, almost simultaneously. The combination of them leads to this error though. I'm applying the least disruptive revert of two possible in https://github.com/apple/swift-package-manager/pull/7196.

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by grynspan** [comment]
Will this break plugins? How can a plugin detect when it should use `URL` instead of the old API?

**Comment by MaxDesiatov** [comment]
The API is additive, thus not expected to break anything. IIUC, plugins using new tools version should use the new API, while old ones should still continue to work.

**Comment by grynspan** [comment]
Thanks!

**Comment by neonichu** [comment]
Yep, plugins declared in packages with tools-version 5.10 and earlier will work exactly as before. When upgrading to 5.11, there'll be deprecation warnings for `Path` based APIs to encourage using the `URL` ones, but they'll still work. We may declare the old APIs as unavailable at some point in the future to force migration to the new APIs, but even then, existing plugins will continue to work.

**Comment by neonichu** [comment]
Ah, the "Applying" message doesn't show on Linux, because it is from "Applying debug entitlements to \(buildProduct.binaryPath.prettyPath())", it isn't about applying the plugin. Code-signing only happens on macOS, of course. I thought otherwise because Xcode *does* have a "Apply build tool plug-in" message that I thought this was.

**Comment by neonichu** [comment]
Was able to resolve the last few deprecation warnings with @tomerd's help -- there was even a small bug hiding in there with an optional property not being set in the URL case.

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
@swift-ci please test package compatibility

**Comment by neonichu** [comment]
@swift-ci please test windows

**Comment by neonichu** [comment]
@swift-ci please test windows

**Comment by neonichu** [comment]
@swift-ci please test windows

**Comment by neonichu** [comment]
@swift-ci please test windows

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Comment by neonichu** [comment]
@swift-ci test windows

**Comment by neonichu** [comment]
Seeing the same test failure on Windows multiple time in a row now, so probably real:

```
Failed Tests (1):
  Swift(windows-x86_64) :: diagnostics/educational_notes_serialization.swift
```

cc @compnerd

**Comment by compnerd** [comment]
It seems to be passing on the swift repository 🤔 CC: @xedin who added this test

**Comment by compnerd** [comment]
Seems to be failing on macOS: https://ci.swift.org/job/apple-llvm-project-pr-macos/4371/console

**Comment by neonichu** [comment]
Sounds like https://github.com/apple/swift/pull/70470 is supposed to fix it.

**Comment by neonichu** [comment]
@swift-ci test windows
