### ISSUE TITLE
SwiftSyntax prebuilt errors - Project no longer compiles on Swift 6.2 nightlies

### ISSUE THREAD

**Issue by MahdiBM** [apple/swift-package-manager#9061]
### Is it reproducible with SwiftPM command-line tools: `swift build`, `swift test`, `swift package` etc?

- [x] Confirmed reproduction steps with SwiftPM CLI. The description text _must_ include reproduction steps with either of command-line SwiftPM commands, `swift build`, `swift test`, `swift package` etc.

### Description

Eversince we had issues upgrading to Swift 6.1 (we still can't use 6.1) we run scheduled nightly tests so we can catch compile issues ahead of Swift minor releases.
The project has recently stopped compiling on 6.2 with these errors:

```
2025-08-26T08:36:50.2378012Z /usr/bin/ld.gold: error: /__w/my-proj/my-proj/.build/prebuilts/swift-syntax/600.0.1/swift-6.2-DEVELOPMENT-SNAPSHOT-2025-08-21-a-MacroSupport-ubuntu_noble_x86_64/lib/libMacroSupport.a(DeclSyntaxParseable.swift.o): multiple definition of '$s11SwiftSyntax013TypeAliasDeclB0V0aB7Builder0eB9ParseableADMc'
2025-08-26T08:36:50.2379173Z /usr/bin/ld.gold: /__w/my-proj/my-proj/.build/x86_64-unknown-linux-gnu/debug/SwiftSyntaxBuilder-tool.build/DeclSyntaxParseable.swift.o: previous definition here
2025-08-26T08:36:50.2380425Z /usr/bin/ld.gold: error: /__w/my-proj/my-proj/.build/prebuilts/swift-syntax/600.0.1/swift-6.2-DEVELOPMENT-SNAPSHOT-2025-08-21-a-MacroSupport-ubuntu_noble_x86_64/lib/libMacroSupport.a(DeclSyntaxParseable.swift.o): multiple definition of '$s18SwiftSyntaxBuilder04DeclB9ParseableTL'
2025-08-26T08:36:50.2381537Z /usr/bin/ld.gold: /__w/my-proj/my-proj/.build/x86_64-unknown-linux-gnu/debug/SwiftSyntaxBuilder-tool.build/DeclSyntaxParseable.swift.o: previous definition here
```

### Expected behavior

No errors.

### Actual behavior

Errors.

### Steps to reproduce

Private project. I can share the full verbose logs privately.

### Swift Package Manager version/commit hash

Not sure of the exact hash

### Swift & OS version (output of `swift --version ; uname -a`)

Latest official nightly Docker images for Swift 6.2.

**Comment by MahdiBM** [comment]
cc @dschaefer2 since you're usually taking care of prebuilts.
Not sure if what i reported is already known.

**Comment by MahdiBM** [comment]
Ok hold on a few hours ... I can see some other dependency-related errors as well.
Let me resolve those errors and see if these'll go away. There is a 50/50 chance these are related. Not really sure.

**Comment by MahdiBM** [comment]
Ok just looking into a bit, I'm not sure if i can resolve these other dependency errors anyway, this easily.
Some of the errors are from outside dependencies of our app and I'll have to fix those first...

```
2025-08-26T08:33:56.7747469Z error: Target EnumeratorMacroImpl imports another target (SwiftParserDiagnostics) in the package without declaring it a dependency.
2025-08-26T08:33:57.7393865Z error: Target DependenciesMacrosPlugin imports another target (SwiftDiagnostics) in the package without declaring it a dependency.
2025-08-26T08:33:57.7891992Z error: Target MaxCharactersMacro imports another target (SwiftCompilerPlugin) in the package without declaring it a dependency.
2025-08-26T08:34:00.6155487Z error: Target MacroTests imports another target (SwiftSyntaxMacrosGenericTestSupport) in the package without declaring it a dependency.
2025-08-26T08:34:02.3905001Z error: Target PostgresRecordMacro imports another target (SwiftCompilerPlugin) in the package without declaring it a dependency.
2025-08-26T08:34:02.6331645Z error: Target SwiftOpenAPIMacros imports another target (SwiftSyntaxMacros) in the package without declaring it a dependency.
2025-08-26T08:34:05.1788968Z error: Target CodableEnumMacro imports another target (SwiftCompilerPlugin) in the package without declaring it a dependency.
```

`DependenciesMacrosPlugin` for example comes from that dependency package from point-free.

To be clear previous Swift versions were all fine without these imports (not saying not throwing errors is the correct behavior, just saying throwing errors like this is breaking our whole dependency chain)

**Comment by MahdiBM** [comment]
This issue is solved in the latest nightlies
