### PR TITLE
Fix two small issues with handling of plugin triples

### PR DESCRIPTION
**Pull request by neonichu**
- We were not stringently using version-less triples in all comparisons
- We were not merging the supported triples of all executable info entries into the final `toolNamesToTriples` which could lead to incorrect errors about unsupported platforms

rdar://101096803

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Review by FranzBusch — APPROVED** [review]

File: Sources/SPMBuildCore/PluginInvocation.swift [hunk 1]
```diff
@@ -373,7 +373,7 @@ extension PackageGraph {
                 let toolNamesToTriples = accessibleTools.reduce(into: [String: [String]](), { dict, tool in
                     switch tool {
                     case .vendedTool(let name, _, let triple):
-                        dict[name] = triple
+                        dict[name, default: []].append(contentsOf: triple)
```
Comment (tomerd) [inline Sources/SPMBuildCore/PluginInvocation.swift:376]: triples?

**Review by tomerd — APPROVED** [review]

**Comment by tomerd** [comment]
possible to add a test?

**Comment by neonichu** [comment]
Not sure what is going in the Windows build:

```
C:\Users\swift-ci\jenkins\workspace\swiftpm-PR-windows\sourcekit-lsp\Sources\LanguageServerProtocol\Messages.swift:24:3: error: cannot find 'CodeActionResolveRequest' in scope

  CodeActionResolveRequest.self,

  ^~~~~~~~~~~~~~~~~~~~~~~~
```

cc @compnerd

**Comment by neonichu** [comment]
BTW, it looks like SourceKit-LSP itself is not running Windows for its CI, that seems wrong. Either it should be removed from SwiftPM's preset as well or it should be running Windows builds on its own PRs. cc @shahmishal

**Comment by neonichu** [comment]
@swift-ci please smoke test windows

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
Ah yes, `PluginInvocationTests.testParseArtifactsDoesNotCheckPlatformVersion` cannot work on non-macOS

**Comment by neonichu** [comment]
@swift-ci please smoke test
