### PR TITLE
Run `getTaskAllowEntitlement` test with release configuration

### PR DESCRIPTION
**Pull request by svmkr-dev**
Reverts change to test arguments introduced in cad6c0fef03df94f4e353460e3a93d2d0aa97d44. 

### Motivation:

`getTaskAllowEntitlement` test was written with intention to run in both debug and release configurations. It's because enable and disable options are valid for both of them, so we can produce release binary with get-task-allow entitlement for profiling and debug binary without entitlement (for whatever reason).

### Modifications:

Revert `getTaskAllowEntitlement` to using `BuildData` struct as test input and generate those inputs with `getBuildData(for:)` function.
Removes issue link to #9745 because #9380 actually resolved that issue.

### Result:

`getTaskAllowEntitlement` test runs for both debug and release build configuration for both build systems.

### CODE REVIEW

**Comment by owenv** [comment]
hmm, yeah that change was accidental, thanks

**Comment by owenv** [comment]
@swift-ci test

**Review by owenv — APPROVED** [review]

**Comment by svmkr-dev** [comment]
@owenv sorry for no activity.
If you could schedule a CI run, I'll take a look and comment on any failures.

**Comment by owenv** [comment]
sorry I lost track of this. Feel free to ping ~once a week in the future if you don't hear back

**Comment by owenv** [comment]
@swift-ci test

**Comment by svmkr-dev** [comment]
All three failures share error message:
```
SWBTaskConstruction/TaskProducer.swift:360: Fatal error: 'try!' expression unexpectedly raised an error: Couldn't load spec with identifier 'com.apple.build-tools.clang-ssaf-linker' in domain
```
(with quoted domain after "domain" being different)
which happens when running bootstrap script.

Also I've just noticed that I made a typo in commit message. Let me know if you want me to fix it before merge.

**Comment by owenv** [comment]
That's an unrelated CI issue, just bad timing

**Comment by owenv** [comment]
@swift-ci test

**Comment by svmkr-dev** [comment]
@owenv pinging to remind

**Comment by svmkr-dev** [comment]
@owenv pinging to remind

**Comment by owenv** [comment]
thanks for the ping, let's merge this
